### ISSUE TITLE
Add community guidelines

### ISSUE THREAD

**Issue by peanutfun** [cgrudz/DataAssimilationBenchmarks.jl#14]
[Community guidelines](https://joss.readthedocs.io/en/latest/review_criteria.html#community-guidelines) are a review criterion of JOSS publications. Please add information to this repository on how to seek support, report issues, and how to contribute. This can be supplied in sections of the `README.md` and in a separate `CONTRIBUTING.md` file. More information on this topic can be found, e.g., in the Github docs: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

openjournals/joss-reviews#4129

**Comment by cgrudz** [comment]
Community guidelines are now included in the main documentation:

https://cgrudz.github.io/DataAssimilationBenchmarks.jl/dev/community/Contributing/

As well as the code of conduct:

https://github.com/cgrudz/DataAssimilationBenchmarks.jl/blob/master/CODE_OF_CONDUCT.md
