### ISSUE TITLE
Add instructions on how to add new DA schemes and models

### ISSUE THREAD

**Issue by peanutfun** [cgrudz/DataAssimilationBenchmarks.jl#15]
The `README.md` lacks instructions on how to extend the framework with new models and new DA schemes. Independently from my suggestion to change how DA schemes can be specified when calling functions of this module (#13), the current way of implementing additions should be documented. For example, the [DAPPER Python library](https://github.com/nansencenter/DAPPER) documents [how to add models](https://github.com/nansencenter/DAPPER/tree/master/dapper/mods#defining-your-own-model) and at least [refers to examples](https://github.com/nansencenter/DAPPER/tree/master/dapper/da_methods#defining-your-own-method) for adding DA schemes. I understand that defining interfaces for DA schemes and models is more difficult in Julia because the language features no classes like in C++ or Python. However, I think that at least a rough implementation guideline should be supplied. This can be done in the `README.md`, or in another document if the instructions become too lengthy.

openjournals/joss-reviews#4129

**Comment by cgrudz** [comment]
Rough guidelines are now included in the documentation:

https://cgrudz.github.io/DataAssimilationBenchmarks.jl/dev/community/Contributing/#Contributing

This is currently being developed piece-wise, due to the small scale of the project at the moment, but with future planning for a more unified refactoring of the codes.

**Comment by peanutfun** [comment]
Thanks! I understand that "injecting" new models is not a goal of this project and I appreciate your effort in managing expectations of users who would want to do so.
