### ISSUE TITLE
Add badges for doc in README

### ISSUE THREAD

**Issue by tmigot** [cgrudz/DataAssimilationBenchmarks.jl#29]
Related to JOSS submission https://github.com/openjournals/joss-reviews/issues/4129

I think it would be great to have a badge instead of the link to the documentation in the readme, and also to "promote" the stable documentation additionally to the master-version.

```
[docs-stable-img]: https://img.shields.io/badge/docs-stable-blue.svg
[docs-stable-url]: https://cgrudz.github.io/DataAssimilationBenchmarks.jl/stable
[docs-dev-img]: https://img.shields.io/badge/docs-dev-purple.svg
[docs-dev-url]: https://cgrudz.github.io/DataAssimilationBenchmarks.jl/dev
```

Let me know if you think it's a good idea.

**Comment by cgrudz** [comment]
Thanks for the suggestion, this is now resolved.
