### ISSUE TITLE
Upper-cases in bibliography

### ISSUE THREAD

**Issue by tmigot** [cgrudz/DataAssimilationBenchmarks.jl#32]
Regarding the review https://github.com/openjournals/joss-reviews/issues/4129

The upper cases should be respected in the bibliography  https://github.com/cgrudz/DataAssimilationBenchmarks.jl/blob/master/paper.bib

For instance, `State-of-the-art stochastic data assimilation methods for high-dimensional non-Gaussian problems` is missing the upper case to `Gaussian`.

**Comment by cgrudz** [comment]
Thanks for the catch, this is now resolved in the latest draft:

https://github.com/openjournals/joss-reviews/issues/4129#issuecomment-1299170192

**Comment by tmigot** [comment]
This one https://dl.acm.org/doi/abs/10.1145/2833157.2833162 also needs upper-cases

**Comment by cgrudz** [comment]
Thanks, missed that.
