### ISSUE TITLE
Add usage examples and workflow to README.md

### ISSUE THREAD

**Issue by peanutfun** [cgrudz/DataAssimilationBenchmarks.jl#7]
The `README.md` documents the API of the module. As the argument lists are quite extensive, I think it would be helpful to add "typical" usage examples for some of the methods and solvers. In particular, this would help to demonstrate some kind of workflow. Starting out with generating a time series, an example could show how to run different data assimilation methods included in this package, and then how to evaluate the output and compare the methods against each other.

Currently, one has to look up a typical argument list in the tests, which is cumbersome.

openjournals/joss-reviews#4129

**Comment by cgrudz** [comment]
I decided to add an additional section that sketches the overall workflow, where the documentation is organized a bit to emulate this workflow precisely:

https://cgrudz.github.io/DataAssimilationBenchmarks.jl/dev/submodules/experiments/Workflow/

This section in the documentation now discusses how one will go from an installation to the point of running a twin experiment following the submodules in the docs.  I think this is now a better solution, though I will certainly take further suggestions on how to clarify the use example of the software.

**Comment by peanutfun** [comment]
Very good, thank you!
